[package]
name = "kova-platform-windows"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
kova-core = { workspace = true }
thiserror = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
windows = { workspace = true }
windows-version = { workspace = true }
image = { version = "0.25.9", default-features = false, features = ["webp", "gif", "png"] }

[dev-dependencies]
